version: "2"
services:
  api:
    container_name: registry.gitlab.com/intellidrone/api
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4.0
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"