version: "3.3"
services:
  api:
    image: registry.gitlab.com/intellidrone/api
    ports:
      - "3000:3000"
    networks:
      - db
    depends_on:
      - mongo
  mongo:
    image: mongo:4.0
#    volumes:
#      - ./data:/data/db
    networks:
      - db

networks:
  db:
    driver: overlay
